/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:4da6e41e-a0d6-4c08-a7e9-d929b46c9285",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_8bISoqPke",
    "aws_user_pools_web_client_id": "62fvvm78o1ijr7ao297qgjun69",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://w433qfegbndphkt3vny7ccueje.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-zdhn4q6qz5hb7fshigctvxtj2i"
};


export default awsmobile;
