/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:4da6e41e-a0d6-4c08-a7e9-d929b46c9285",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_8bISoqPke",
    "aws_user_pools_web_client_id": "62fvvm78o1ijr7ao297qgjun69",
    "oauth": {}
};


export default awsmobile;
